### ISSUE TITLE
'colorfield' not needed since django 4.0

### ISSUE THREAD

**Issue by bmull** [fabiocaccamo/django-colorfield#158]
**Python version**
3.11.2

**Django version**
4.1

**Package version**
0.10.2

**Current behavior (bug description)**
When I try to run server, I get this traceback

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/.../venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/.../venv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/.../venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/.../venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/.../venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/.../venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/.../venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/Users/.../venv/lib/python3.11/site-packages/admin_interface/apps.py", line 22, in ready
    settings.check_installed_apps()
  File "/Users/.../venv/lib/python3.11/site-packages/admin_interface/settings.py", line 26, in check_installed_apps
    check_installed_app('colorfield', (4, 0))
  File "/Users/.../venv/lib/python3.11/site-packages/admin_interface/settings.py", line 19, in check_installed_app
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'colorfield' not needed since django 4.0, remove it from settings.INSTALLED_APPS.

```

**Expected behavior**
Server loads

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-colorfield/issues/158">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/158/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/158/pledge.svg">
</picture>
</a>

**Comment by bmull** [comment]
I'm an idiot. Upgraded django-admin-interface

**Comment by fabiocaccamo** [comment]
It happens, no problem! 😂
