### ISSUE TITLE
Version 0.1.17 cannot be installed - README.md missing in package

### ISSUE THREAD

**Issue by kilrogg** [fabiocaccamo/django-colorfield#46]
```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-F9fkD5/django-colorfield/setup.py", line 3, in <module>
    with open("README.md") as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.md'
```

Seems like MANIFEST.in still references README.rst

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?
