### ISSUE TITLE
subclasses of Widget must provide a render() method

### ISSUE THREAD

**Issue by marti1125** [fabiocaccamo/django-colorfield#70]
**Python version**
2.7.18

**Django version**
1.8

**Package version**
0.4.2

**Current behavior (bug description)**
```
app_1     | Internal Server Error: /admin/{{form}}/add/
app_1     | Traceback (most recent call last):
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
app_1     |     response = response.render()
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
app_1     |     self.content = self.rendered_content
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
app_1     |     content = template.render(context, self._request)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
app_1     |     return self.template.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
app_1     |     return self._render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
app_1     |     return self.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
app_1     |     return compiled_parent._render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
app_1     |     return self.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
app_1     |     return compiled_parent._render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
app_1     |     return self.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
app_1     |     result = block.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
app_1     |     result = block.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
app_1     |     nodelist.append(node.render(context))
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 159, in render
app_1     |     return template.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 211, in render
app_1     |     return self._render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
app_1     |     return self.nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
app_1     |     nodelist.append(node.render(context))
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
app_1     |     nodelist.append(node.render(context))
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
app_1     |     return nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
app_1     |     return nodelist.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
app_1     |     bit = self.render_node(node, context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
app_1     |     return node.render(context)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 92, in render
app_1     |     output = force_text(output)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 92, in force_text
app_1     |     s = six.text_type(s)
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/utils/html.py", line 390, in <lambda>
app_1     |     klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 543, in __str__
app_1     |     return self.as_widget()
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 599, in as_widget
app_1     |     return force_text(widget.render(name, self.value(), attrs=attrs))
app_1     |   File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 209, in render
app_1     |     raise NotImplementedError('subclasses of Widget must provide a render() method')
app_1     | NotImplementedError: subclasses of Widget must provide a render() method
```

**Expected behavior**
works like the doc.

**Comment by fabiocaccamo** [comment]
@marti1125 could you provide a failing test please? In this way we avoid regressions.

**Comment by fabiocaccamo** [comment]
@marti1125 you can upgrade to `0.4.3` version, please let me know if the problem persists.
